### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by yongming9011** [martin90s/ImagePicker#2]
希望作者可以考虑加入再次进入选择界面时默认选中上次已选择过的图片。

**Comment by martin90s** [comment]
@yongming9011 这个现在使用者可以自己存一下，因为打开的图片选择器的时候可以传入你已经选中的图片。
有一个setSelected(List<String>)的接口，可以实现你说的功能。

**Comment by yongming9011** [comment]
@martin90s OK，刚才没看到这个方法，赞一个！
