### ISSUE TITLE
FileUriExposedException

### ISSUE THREAD

**Issue by f3401pal** [martin90s/ImagePicker#4]
When target SDK 24+, crash and throws FileUriExposedException when choose to use camera.
https://github.com/martin90s/ImagePicker/blob/master/imagepicker/src/main/java/com/imnjh/imagepicker/CapturePhotoHelper.java#71

Us this instead
```
Uri uri = FileProvider.getUriForFile(context, context.getApplicationContext().getPackageName() + ".provider", this.photoFile);
```

**Comment by martin90s** [comment]
@f3401pal Thanks a lot！

**Comment by martin90s** [comment]
@f3401pal new release has fix this error

**Comment by f3401pal** [comment]
Thank you.
